name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set executable permission to gradlew
        run: chmod +x zadanie10/backend/gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          cd zadanie10/backend
          ./gradlew build

      - name: Run tests
        run: |
          cd zadanie10/backend
          ./gradlew test

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Application Build Notification'
          body: 'The application was successfully built and tested.'
          from: ${{ secrets.EMAIL_ADDRESS }}
          fromname: 'Build Notification'
          to: ${{ secrets.EMAIL_TO }}